version: "3.6"

#### Templates ####
x-logging-common: &logging-common
  logging:
    options:
      max-size: '10m'
      max-file: '3'

services:
  build_system:
    container_name: build_system
    image: build_system
    build: .
    command: sh -c "pytest && uvicorn main:app --host=0.0.0.0 --port=8000"
    expose:
      - 8000
    volumes:
      - ./builds/:/app/builds
    restart: always
    <<: *logging-common

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
    <<: *logging-common